# Change these first
owner: geored # Your GitHub username
repo: test-git-actions # Your Github repository name

# Add your sites here
sites:
  - name:  Indy Static Prod
    url: http://indy.psi.redhat.com
    headers:
      - "Authorization: Bearer $INDY_TOKEN"
  - name: Indy Prod
    url: http://indy-admin.psi.redhat.com
    headers:
      - "Authorization: Bearer  $INDY_TOKEN"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Indy Check"
  introMessage: "Check if indy static and prod sites are up and running and also latencies"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
